version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    container_name: sqlserver_container
    environment:
      MSSQL_SA_PASSWORD: Password2024#
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    volumes:
      - C:/Users/juanc/OneDrive/Documentos/Docker/Volumenes/sqlserver_data:/var/opt/mssql/data
    ports:
      - 1400:1433